// This is just the data of the pokemon!
export const pokemonData = [
    {
        id: 1,
        pkmnId: 143,
        name: 'Gengar',
        type: ['ghost', 'poison'],
        img: 'gengar.png',
        description: 'On the night of a full moon, if shadows move on their own and laugh, it must be Gengars doing.',
    },
    {
        id: 2,
        pkmnId: 427,
        name: 'Buneary',
        type: ['normal'],
        img: 'buneary.png',
        description: 'When it senses danger, it perks up its ears. On cold nights, it sleeps with its head tucked into its fur.',
    },
    {
        id: 3,
        pkmnId: 869,
        name: 'Alcreamie',
        type: ['fairy'],
        img: 'alcreamie.png',
        description: 'When it trusts a Trainer, it will treat them to berries it has decorated with cream.',
    },
    {
        id: 4,
        pkmnId: 448,
        name: 'Lucario',
        type: ['fighting', 'steel'],
        img: 'lucario.png',
        description: 'It controls waves known as auras, which are powerful enough to pulverize huge rocks. It uses these waves to take down its prey.',
    },
    {
        id: 5,
        pkmnId: 376,
        name: 'Metagross',
        type: ['steel', 'psychic'],
        img: 'metagross.png',
        description: 'Metagross is the result of the fusion of two Metang. This Pokémon defeats its opponents through use of its supercomputer-level brain.',
    },
    {
        id: 6,
        pkmnId: 707,
        name: 'Klefki',
        type: ['steel', 'fairy'],
        img: 'klefki.png',
        description: 'This Pokémon is constantly collecting keys. Entrust a Klefki with important keys, and the Pokémon will protect them no matter what.',
    },
    {
        id: 7,
        pkmnId: 9,
        name: 'Blastoise',
        type: ['water'],
        img: 'blastoise.png',
        description: 'The rocket cannons on its shell fire jets of water capable of punching holes through thick steel.',
    },
    {
        id: 8,
        pkmnId: 26,
        name: 'Raichu',
        type: ['electric'],
        img: 'raichu.png',
        description: 'If its electric pouches run empty, it raises its tail to gather electricity from the atmosphere.',
    },
    {
        id: 9,
        pkmnId: 38,
        name: 'Ninetales',
        type: ['fire'],
        img: 'ninetales.png',
        description: 'It is said to live 1,000 years, and each of its tails is loaded with supernatural powers.',
    },
    {
        id: 10,
        pkmnId: 453,
        name: 'Croagunk',
        type: ['poison', 'fighting'],
        img: 'croagunk.png',
        description: 'It makes frightening noises with its poison-filled cheek sacs. When opponents flinch, Croagunk hits them with a poison jab.',
    },
    {
        id: 11,
        pkmnId: 724,
        name: 'Decidueye',
        type: ['grass', 'ghost'],
        img: 'decidueye.png',
        description: 'In a tenth of a second, it can nock and fire an arrow quill, piercing an opponents weak point before they notice what is happening.',
    },
    {
        id: 12,
        pkmnId: 157,
        name: 'Typhlosion',
        type: ['fire'],
        img: 'typhlosion.png',
        description: 'Typhlosion obscures itself behind a shimmering heat haze that it creates using its intensely hot flames. This Pokémon creates blazing explosive blasts that burn everything to cinders.',
    },
    {
        id: 13,
        pkmnId: 190,
        name: 'Aipom',
        type: ['normal'],
        img: 'aipom.png',
        description: 'It searches for prey from the tops of trees. When it spots its favorite food, Bounsweet, Aipom gets excited and pounces.',
    },
    {
        id: 14,
        pkmnId: 359,
        name: 'Absol',
        type: ['dark'],
        img: 'absol.png',
        description: 'Swift as the wind, Absol races through fields and mountains. Its curved, bow-like horn is acutely sensitive to the warning signs of natural disasters.',
    },
    {
        id: 15,
        pkmnId: 471,
        name: 'Glaceon',
        type: ['ice'],
        img: 'glaceon.png',
        description: 'Any who become captivated by the beauty of the snowfall that Glaceon creates will be frozen before they know it.',
    },
    {
        id: 16,
        pkmnId: 195,
        name: 'Quagsire',
        type: ['water', 'ground'],
        img: 'quagsire.png',
        description: 'Its body is always slimy. It often bangs its head on the river bottom as it swims but seems not to care.',
    },
];